name: Feature Request
description: Suggest a new feature for the Liquid Edge LLN Kit
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature
      placeholder: Add support for...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: This would enable...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Core Neural Network Layers
        - Hardware Deployment
        - ROS2 Integration  
        - Energy Optimization
        - Benchmarking Tools
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: How would you like to see this implemented?
      placeholder: |
        1. Add new module...
        2. Extend existing API...
        3. Create CLI command...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature
        - label: I need help implementing this feature
        - label: This is just a suggestion