apiVersion: v1
kind: Service
metadata:
  name: liquid-edge-lln-service
  namespace: production
  labels:
    app: liquid-edge-lln
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: liquid-edge-lln
