name: liquid-edge-dev
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Core Python
  - python=3.11
  - pip
  
  # Scientific computing
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  
  # Machine Learning - JAX ecosystem
  - jax>=0.4.28
  - flax>=0.8.0
  - optax>=0.2.0
  
  # Alternative ML frameworks for compatibility
  - pytorch>=2.0.0
  - torchvision
  - tensorflow>=2.15.0
  
  # Data visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  - bokeh>=3.2.0
  
  # Jupyter ecosystem
  - jupyter
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0
  - notebook>=7.0.0
  
  # Development tools
  - black>=23.0.0
  - ruff>=0.1.0
  - mypy>=1.6.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-xdist>=3.3.0
  
  # Documentation
  - sphinx>=7.0.0
  - myst-parser>=2.0.0
  
  # Hardware interface libraries
  - pyserial>=3.5
  - pybluez  # Bluetooth support
  
  # Computer vision (for robotics)
  - opencv>=4.8.0
  - pillow>=10.0.0
  
  # Audio processing (for sensor applications)
  - librosa>=0.10.0
  - soundfile>=0.12.0
  
  # Networking and web
  - requests>=2.31.0
  - aiohttp>=3.8.0
  - websockets>=11.0.0
  
  # Data formats
  - h5py>=3.9.0
  - zarr>=2.16.0
  - netcdf4>=1.6.0
  
  # System monitoring
  - psutil>=5.9.0
  
  # Cryptography and security
  - cryptography>=41.0.0
  - pycryptodome>=3.18.0
  
  # Database
  - sqlalchemy>=2.0.0
  - sqlite
  
  # Cloud and deployment
  - boto3>=1.28.0
  - docker-py>=6.1.0
  
  # Development utilities
  - tqdm>=4.65.0
  - rich>=13.0.0
  - click>=8.1.0
  - pydantic>=2.0.0
  
  # Configuration management
  - pyyaml>=6.0.0
  - toml>=0.10.0
  
  # Profiling and debugging
  - line_profiler>=4.0.0
  - memory_profiler>=0.61.0
  
  # Parallel computing
  - joblib>=1.3.0
  - dask>=2023.8.0
  
  # Package and environment management
  - conda-build
  - conda-verify
  
  # Git and version control
  - git
  - git-lfs
  
  # System libraries
  - libgcc-ng
  - libstdcxx-ng
  
  # Additional pip packages
  - pip:
    # Liquid Edge specific dependencies
    - jaxlib>=0.4.28
    
    # Advanced ML tools
    - wandb>=0.15.0
    - mlflow>=2.7.0
    - optuna>=3.3.0
    
    # Hardware simulation
    - qemu-python>=0.1.0
    
    # Embedded development
    - esptool>=4.6.0
    - pyocd>=0.36.0
    
    # Additional testing tools
    - hypothesis>=6.82.0
    - factory-boy>=3.3.0
    - freezegun>=1.2.0
    
    # Code quality
    - pre-commit>=3.4.0
    - commitizen>=3.7.0
    
    # Documentation enhancement
    - sphinx-autoapi>=3.0.0
    - sphinx-copybutton>=0.5.0
    - furo>=2023.8.0
    
    # Monitoring and observability
    - prometheus-client>=0.17.0
    - opentelemetry-api>=1.20.0
    - opentelemetry-sdk>=1.20.0
    
    # Security tools
    - bandit[toml]>=1.7.0
    - safety>=2.3.0
    - pip-audit>=2.6.0
    
    # API development
    - fastapi>=0.103.0
    - uvicorn[standard]>=0.23.0
    - pydantic[email]>=2.3.0
    
    # Containerization
    - docker>=6.1.0
    
    # Database drivers
    - asyncpg>=0.28.0
    - aiosqlite>=0.19.0
    
    # Message queues
    - celery[redis]>=5.3.0
    
    # Robotics (if ROS2 is available)
    # - rclpy  # Uncomment if ROS2 is needed
    
    # Edge AI optimization
    - onnx>=1.14.0
    - onnxruntime>=1.15.0